#### 1
Research Question - What question am I awnswering

#### 2
Dataset

Preprocessing

Analysis

In [4]:
import pandas as pd
import numpy as np
import os
print("Search file in", os.getcwd())
df = pd.read_csv("heart.csv")
df.head()
# Selecting the first 2 rows df[0:2]
print(df["cp"])
print("Shape:",df.shape)
df.describe()

# Save data df.to_csv("./data/data2.xlsx")

Search file in /home/alex/Desktop/Heart Disease
0      3
1      2
2      1
3      1
4      0
      ..
298    0
299    3
300    0
301    0
302    1
Name: cp, Length: 303, dtype: int64
Shape: (303, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

## Incorrect definitions
Defintion on Kaggle is the following.

"The "goal" field refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4." [Link to dataset](https://www.kaggle.com/ronitf/heart-disease-uci)

### Using the description from the UCI dataset [Reference](https://archive.ics.uci.edu/ml/datasets/Heart+Disease)
#### Value 0: No chest pain
There is no chest pain.
#### Value 1: typical angina (Chest pain)
[Reference 1](https://www.heart.org/en/health-topics/heart-attack/angina-chest-pain) [Reference 2](https://www.timeofcare.com/typical-vs-atypical-chest-pain/)
Usually physical exertion or emotional destress. This is a symptom usually of coronary heart disease which is constriction of the Usually physical exertion or emotional destress. This is a symptom usually of coronary heart disease which is constriction of the arteries.

If releived by rest or nitroglycerine to relax the arteries. 
**This is usually caused by heart disease.**

#### Value 2: atypical angina (Chest pain)
[Refrence 1](https://www.timeofcare.com/typical-vs-atypical-chest-pain/)
Does not fit all 3 requirements of typical angina.

**Could be heart disease or other conditions such as lung problems as the heart is not getting enough oxygen.**

#### Value 3: non-anginal pain (Non-chest pain)
Pain is the term that is used to describe pain in the chest that is not caused by heart disease or a heart attack. [Refrenece](https://my.clevelandclinic.org/health/diseases/15851-gerd-non-cardiac-chest-pain)

Simmilar to atypical angina but has a duration of 30 minutes or less than 5 seconds and caused by moving arms or toroso. It also can be reloved immediatly by laying down. [Reference](https://pubmed.ncbi.nlm.nih.gov/2255129/)

**Not caused by heart disease.**
#### Value 4: asymptomatic heart disease
**Asymptomatic heart disease.**

## The "cp" column is for chest pain and not heart disease...

### In the acutal documentation of the UCI dataset
[Reference](https://archive.ics.uci.edu/ml/datasets/Heart+Disease)

58 num: diagnosis of heart disease (angiographic disease status)
-- Value 0: < 50% diameter narrowing
-- Value 1: > 50% diameter narrowing 

This means that the 14th attribute target is the heart disease indicator not the "cp" collumn.

Compareing data to orignal dataset. 

As the orginal dataset was corrupted the first 3

In [115]:
import operator
data = '1 0 63 1 -9 -9 -9 -9 1 145 1 233 -9 50 20 1 -9 1 2 2 3 81 0 0 0 0 0 1 10.5 6 13 150 60 190 90 145 85 0 0 2.3 3 -9 172 0 -9 -9 -9 -9 -9 -9 6 -9 -9 -9 2 16 81 0 1 1 1 -9 1 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name 2 0 67 1 -9 -9 -9 -9 4 160 1 286 -9 40 40 0 -9 1 2 3 5 81 0 1 0 0 0 1 9.5 6 13 108 64 160 90 160 90 1 0 1.5 2 -9 185 3 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 2 5 81 2 1 2 2 -9 2 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name 3 0 67 1 -9 -9 -9 -9 4 120 1 229 -9 20 35 0 -9 1 2 2 19 81 0 1 0 0 0 1 8.5 6 10 129 78 140 80 120 80 1 0 2.6 2 -9 150 2 -9 -9 -9 -9 -9 -9 7 -9 -9 -9 2 20 81 1 1 1 1 -9 1 -9 1 -9 2 2 1 1 1 7 3 -9 -9 name 4 0 37 1 -9 -9 -9 -9 3 130 0 250 -9 0 0 0 -9 1 0 2 13 81 0 1 0 0 0 1 13 13 17 187 84 195 68 130 78 0 0 3.5 3 -9 167 0 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 2 4 81 0 1 1 1 -9 1 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name 6 0 41 0 -9 -9 -9 -9 2 130 1 204 -9 0 0 0 -9 1 2 2 7 81 0 0 0 0 0 1 7 -9 9 172 71 160 74 130 86 0 0 1.4 1 -9 40 0 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 2 18 81 0 1 1 1 -9 1 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name 7 0 56 1 -9 -9 -9 -9 2 120 1 236 -9 20 20 0 -9 1 0 3 9 81 1 0 0 0 0 1 11.3 -9 16 178 73 165 70 120 75 0 0 0.8 1 -9 127 0 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 3 10 81 0 1 1 1 -9 1 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name 8 0 62 0 -9 -9 -9 -9 4 140 0 268 -9 0 0 0 -9 1 2 1 28 81 0 0 0 0 0 1 6 6 7 160 83 180 84 140 100 0 0 3.6 3 -9 122 2 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 2 2 81 3 1 2 1 -9 1 -9 2 -9 2 1 1 1 1 7 1 -9 -9 name'

dataArray = data.split(' ')

#How many elements are in the array as every 76 elements there is a new one.
print((len(dataArray)+1)/76)




data1 = '1 0 63 1 -9 -9 -9 -9 1 145 1 233 -9 50 20 1 -9 1 2 2 3 81 0 0 0 0 0 1 10.5 6 13 150 60 190 90 145 85 0 0 2.3 3 -9 172 0 -9 -9 -9 -9 -9 -9 6 -9 -9 -9 2 16 81 0 1 1 1 -9 1 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name'
data2 = '2 0 67 1 -9 -9 -9 -9 4 160 1 286 -9 40 40 0 -9 1 2 3 5 81 0 1 0 0 0 1 9.5 6 13 108 64 160 90 160 90 1 0 1.5 2 -9 185 3 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 2 5 81 2 1 2 2 -9 2 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name'

dataArray1 = data1.split(' ')
dataArray2 = data2.split(' ')
print(len(dataArray1))
print(len(dataArray2))
print(dataArray1[57])
print(dataArray2[57])

ageFind = 2
findTPS = 9
findHD = 57
for x in range(int((len(dataArray)+1)/76)):
    print('Age: ' + dataArray[ageFind])
    print('TPS: ' + dataArray[findTPS])
    print('Heart disease result: ' + dataArray[findHD])
    print('Found in: ' + (str(findHD)))
    ageFind = ageFind + 76
    findHD = findHD + 76
    findTPS = findTPS + 76

7.0131578947368425
76
76
0
2
Age: 63
TPS: 145
Heart disease result: 0
Found in: 57
Age: 67
TPS: 160
Heart disease result: 2
Found in: 133
Age: 67
TPS: 120
Heart disease result: 1
Found in: 209
Age: 37
TPS: 130
Heart disease result: 0
Found in: 285
Age: 41
TPS: 130
Heart disease result: 0
Found in: 361
Age: 56
TPS: 120
Heart disease result: 0
Found in: 437
Age: 62
TPS: 140
Heart disease result: 3
Found in: 513

#### 3
Visualisation

#### 4 (The rest can be breif but this one should be the main part)
Analyse - What did you predict and how did you predict it

#### 5
Results

In [ ]:
Conclusion