#### 1
Research Question - What question am I awnswering

#### 2
Dataset

Preprocessing

Analysis

In [4]:
import pandas as pd
import numpy as np
import os
print("Search file in", os.getcwd())
df = pd.read_csv("heart.csv")
df.head()
# Selecting the first 2 rows df[0:2]
print(df["cp"])
print("Shape:",df.shape)
df.describe()

# Save data df.to_csv("./data/data2.xlsx")

Search file in /home/alex/Desktop/Heart Disease
0      3
1      2
2      1
3      1
4      0
      ..
298    0
299    3
300    0
301    0
302    1
Name: cp, Length: 303, dtype: int64
Shape: (303, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

## Incorrect definitions
Defintion on Kaggle is the following.

"The "goal" field refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4." [Link to dataset](https://www.kaggle.com/ronitf/heart-disease-uci)

### Using the description from the UCI dataset [Reference](https://archive.ics.uci.edu/ml/datasets/Heart+Disease)
#### Value 0: No chest pain
There is no chest pain.
#### Value 1: typical angina (Chest pain)
[Reference 1](https://www.heart.org/en/health-topics/heart-attack/angina-chest-pain) [Reference 2](https://www.timeofcare.com/typical-vs-atypical-chest-pain/)
Usually physical exertion or emotional destress. This is a symptom usually of coronary heart disease which is constriction of the Usually physical exertion or emotional destress. This is a symptom usually of coronary heart disease which is constriction of the arteries.

If releived by rest or nitroglycerine to relax the arteries. 
**This is usually caused by heart disease.**

#### Value 2: atypical angina (Chest pain)
[Refrence 1](https://www.timeofcare.com/typical-vs-atypical-chest-pain/)
Does not fit all 3 requirements of typical angina.

**Could be heart disease or other conditions such as lung problems as the heart is not getting enough oxygen.**

#### Value 3: non-anginal pain (Non-chest pain)
Pain is the term that is used to describe pain in the chest that is not caused by heart disease or a heart attack. [Refrenece](https://my.clevelandclinic.org/health/diseases/15851-gerd-non-cardiac-chest-pain)

Simmilar to atypical angina but has a duration of 30 minutes or less than 5 seconds and caused by moving arms or toroso. It also can be reloved immediatly by laying down. [Reference](https://pubmed.ncbi.nlm.nih.gov/2255129/)

**Not caused by heart disease.**
#### Value 4: asymptomatic heart disease
**Asymptomatic heart disease.**

## The "cp" column is for chest pain and not heart disease...

### In the acutal documentation of the UCI dataset
[Reference](https://archive.ics.uci.edu/ml/datasets/Heart+Disease)

58 num: diagnosis of heart disease (angiographic disease status)
-- Value 0: < 50% diameter narrowing
-- Value 1: > 50% diameter narrowing 

This means that the 14th attribute target is the heart disease indicator not the "cp" collumn.

Compareing data to orignal dataset. 

As the orginal dataset was corrupted the first 3

In [80]:
import operator
data = '1 0 63 1 -9 -9 -9 -9 1 145 1 233 -9 50 20 1 -9 1 2 2 3 81 0 0 0 0 0 1 10.5 6 13 150 60 190 90 145 85 0 0 2.3 3 -9 172 0 -9 -9 -9 -9 -9 -9 6 -9 -9 -9 2 16 81 0 1 1 1 -9 1 -9 1 -9 1 1 1 1 1 1 1 -9 -9 name 2 0 67 1 -9 -9 -9 -9 4 160 1 286 -9 40 40 0 -9 1 2 3 5 81 0 1 0 0 0 1 9.5 6 13 108 64 160 90 160 90 1 0 1.5 2 -9 185 3 -9 -9 -9 -9 -9 -9 3 -9 -9 -9 2 5 81 2 1 2 2 -9 2-9 1 -9 1 1 1 1 1 1 1 -9 -9 name'

dataArray = data.split(' ')

print((len(dataArray)+1)/76)

data = 2
for x in range((len(dataArray)+1)/76):
    print('Age: ' + dataArray[data])
    data = data + 76

2.0

TypeError: 'float' object cannot be interpreted as an integer

#### 3
Visualisation

#### 4 (The rest can be breif but this one should be the main part)
Analyse - What did you predict and how did you predict it

#### 5
Results

In [ ]:
Conclusion